'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {supabase} from '@/lib/supabase'

type Order={id:string;order_number:string;status:string;payment_status:string;subtotal:number;shipping:number;total:number;address:any;created_at:string;order_items:{id:string;product_name:string;quantity:number;price:number;variant:string|null}[]}
const labels:Record<string,string>={pending:'Order received',confirmed:'Confirmed',packed:'Packed',shipped:'Shipped',delivered:'Delivered',cancelled:'Cancelled'}
const steps=['pending','confirmed','packed','shipped','delivered']
export default function Orders(){const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{(async()=>{if(!supabase){setError('Supabase is not configured.');setLoading(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){setError('Please login to see your orders.');setLoading(false);return}const{data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,subtotal,shipping,total,address,created_at,order_items(id,product_name,quantity,price,variant)').eq('user_id',user.id).order('created_at',{ascending:false});if(error)setError(error.message);else setOrders((data||[]) as Order[]);setLoading(false)})()},[])
 return <main className="container section"><Link href="/">← Store</Link><div className="sectionhead" style={{marginTop:16}}><div><span className="pill">ACCOUNT</span><h1>My Orders 📦</h1></div><Link className="btn secondary" href="/products">Shop More</Link></div>{loading?<div className="card info">Loading your orders…</div>:error?<div className="card info"><h3>{error}</h3><Link href="/login" className="btn">Login</Link></div>:orders.length===0?<div className="card info"><h3>No orders yet</h3><p className="muted">Your orders and delivery status will appear here.</p><Link href="/products" className="btn">Start Shopping</Link></div>:<div style={{display:'grid',gap:18}}>{orders.map(o=>{const current=steps.indexOf(o.status);return <article className="card info" key={o.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><span className="pill">{labels[o.status]||o.status}</span><h2 style={{margin:'10px 0 4px'}}>#{o.order_number}</h2><small className="muted">{new Date(o.created_at).toLocaleString('en-IN')}</small></div><div><b style={{fontSize:22}}>₹{Number(o.total).toFixed(0)}</b><div className="muted">Payment: {o.payment_status}</div></div></div>{o.status!=='cancelled'&&<div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:4,margin:'22px 0'}}>{steps.map((s,i)=><div key={s} style={{textAlign:'center',fontSize:11,opacity:i<=current?1:.35}}><div style={{height:8,borderRadius:8,background:i<=current?'#9b3f16':'#eadbc8',marginBottom:6}}/><b>{labels[s]}</b></div>)}</div>}<hr/><div style={{display:'grid',gap:8}}>{o.order_items?.map(i=><div key={i.id} style={{display:'flex',justifyContent:'space-between',gap:10}}><span>{i.product_name} × {i.quantity}{i.variant?` • ${i.variant}`:''}</span><b>₹{Number(i.price)*i.quantity}</b></div>)}</div><p className="muted" style={{marginBottom:0}}>Delivery: {o.address?.name}, {o.address?.line1}, {o.address?.city}, {o.address?.state} - {o.address?.pincode}</p></article>})}</div>}</main>}
